---
title: "Material_and_Methods"
author: "Meeyoung Park"
date: "March 24, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Materials and Methods

**Mice**
Male mice consisted of six strains/genotypes: BKS-wt, BKS-db/+, BL6-wt, BL6-db/+, BTBR-wt, and BTBR-ob/+ mice (C57BLKS/J #000662, BKS.Cg-Dock7m +/+ Leprdb/J #000642, C57BL/6J #000664, B6.BKS(D)-Leprdb/J #000697, BTBR T+ Itpr3tf/J #002282 and BTBR.Cg-Lepob/WiscJ #004824, respectively; Jackson Laboratory, Bar Harbor, ME). Mice were fed a standard diet (SD) or a HFD (#D12540-B, 10% kcal fat; #05090701, 54% kcal fat from lard; Research Diets, New Brunswick, NJ). Animals were maintained in a pathogen-free environment and cared for by the University of Michigan (U-M) Unit for Laboratory Animal Medicine. All protocols were approved by the U-M University Committee on Use and Care of Animals and followed Diabetic Complications Consortium guidelines <https://www.diacomp.org/shared/protocols.aspx>.

**Metabolic/Lipid Phenotyping**
Body weights, fasting blood glucose (FBG; 4 h fast), and glucose tolerance testing (GTT) was performed longitudinally; FBG was measured using an AlphaTrak Glucometer (Abbott Laboratories, Abbott Park, IL) and blood glucose was monitored over 2 h post-administration of a glucose bolus (2 g/kg body weight i.p.). Terminal glycated hemoglobin (%GHb) was measured by the Chemistry Core at the Michigan Diabetes Research Center. A Mouse Metabolic Phenotyping Center (MMPC; Vanderbilt University, Nashville, TN; University of Cincinnati, Cincinnati, OH) determined fasting plasma insulin, triglycerides, and cholesterol and performed fast protein liquid chromatography (FPLC) analysis for cholesterol and triglyceride lipoprotein profiles. Plasma was diluted 1:200 and oxidized low density lipoprotein (oxLDL) was quantified via ELISA per the manufacturer’s instructions (#CSB-E07933m, American Research Products, Waltham, MA). Histomorphological assessment of epididymal white adipose tissue (WAT) was determined using Metamorph Image Analysis Software as previously described (29).

**Neuropathy Phenotyping**
Neuropathy phenotyping was performed according to Diabetic Complications Consortium guidelines (30; 31). Sural and sciatic NCVs and intraepidermal nerve fiber density (IENFD) profiles were determined as previously described (13; 32). For sural nerve myelinated fiber density (SNMFD), samples were immersed in 4% paraformaldehyde, 2.5% glutaraldehyde in PBS, pH 7.4, rinsed and embedded in resin. Three 0.5 µm-thick sections were cut from the distal and proximal end of the sural nerve and stained with toluidine blue. Images were captured using a Nikon Microphot-FXA upright microscope and analyzed using Metamorph, version 7.7.0.8 (Molecular Devices, Sunnyvale, CA). Samples were imaged with a 60x oil objective. The number of myelinated fibers and the area of each nerve section were determined manually. The ratio of fibers per area was averaged for six sections to determine final SNMFD.

**Lipidomics**
Samples for untargeted lipiomics analysis are stored at -80°C until analyzed. The lipids are extracted using a modified Bligh-Dyer method. The extraction is carried using 2:2:2 (v/v/v) water/methanol/dichloromethane at room temperature after spiking internal standards (Table 1). The organic layer is collected and dried completely under the stream of nitrogen. Dried extract is re-suspended in 100 µL of solvent B. The lipid extract is injected onto a 1.8 μm particle 50 × 2.1 mm id Waters Acquity HSS T3 column (Waters, Milford, MA) which is heated to 55°C. Elution is performed using acetonitrile / water (40:60, v/v) with 10 mM ammonium acetate  as solvent A and acetonitrile / water / isopropanol (10 : 5 : 85 v/v) with 10 mM ammonium acetate as solvent B. Column is equilibrated for 3 min before the next injection making total run time 19 min. Data are acquired in positive and negative mode using data-dependent MS/MS with dynamic mass exclusion. Pooled human plasma sample and pooled experimental sample (prepared by combining small aliquots of all client’s samples) are used to control the quality of sample preparation and analysis. Randomization scheme is used to distribute pooled samples within the set. Mixture of pure authentic standards is used to monitor the instrument performance on a regular basis.

**Lipidomics Data Analysis**
Lipids are identified using LIPIDBLAST package <http://fiehnlab.ucdavis.edu/projects/LipidBlast> - computer-generated tandem MS library of 212,516 spectra covering 119,200 compounds representing 26 lipid classes, including phospholipids, glycerolipids, bacterial lipoglycans and plant glycolipids. Quantification of lipids is done by Multiquant software (AB-SCIEX). The preprocessing of lipidomics data including normalization using internalstandards and Principal Component Analysis (PCA) analysis was performed to examined the separation of samples. Functional analysis was performed using Ingenuity Pathway Analysis <http://ingenuity.com>.

**Statistical Analyses**
Statistical analyses were performed using GraphPad Prism Software, Version 6 (GraphPad Software, La Jolla, California). Longitudinal comparisons between multiple groups were performed using two-way ANOVA with Tukey’s post-test for multiple comparisons. Cross-section comparisons between multiple groups were performed using one-way ANOVA with Tukey’s post-test for multiple comparisons, or Kruskal-Wallis test with Dunn’s post-test for multiple comparisons, as applicable (33). Assumptions about Gaussian distribution of data and rules for transformation of non-normative data were made as previously described (34). Significance was assigned when p < 0.05. Values represent the mean ± SEM. For lipidomics data, *t-test* was used between two groups.
