---
title: "Lipidomics Analysis on High fat diet mice model"
author: "Meeyoung Park"
date: "March 24, 2016"
output: html_document
---
## Introduction

**Aims/hypothesis:** Patients with impaired glucose tolerance (IGT) are prone to developing peripheral neuropathy (PN), a common complication observed in diabetic patients. To investigate the mechanisms of PN in IGT, appropriate animal models are required. Using mice of various strains/backgrounds, our aim was to identify a model that developed an early and robust neuropathy when placed on a high-fat diet (HFD).

**Methods:** Neuropathy development in six mouse strains/genotypes (BKS-wt, BKS-db/+, BL6-wt, BL6-db/+, BTBR-wt, BTBR-ob/+) fed a 54% HFD was investigated. Lipidomics data from nerve, liver, and plasma for each mouse strain were analyzed.

**Results:** All HFD-fed mice developed PN; however, a more robust neuropathic phenotype consisting of large fiber dysfunction and small fiber degeneration occurred consistently in HFD-fed BL6-wt mice.   

**Conclusions/interpretation:** We conclude that HFD-fed BL6-wt mice are a favorable model for investigating PN during a state of IGT.
