Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Plasma_db_BTBR_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Liver_db_BTBR_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/SCN_db_BTBR_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Liver_db_BL6_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Plasma_db_BL6_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Plasma_db_BKS_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/SCN_db_BL6_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Liver_db_BKS_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Plasma_WT_BTBR_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/SCN_db_BKS_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Liver_WT_BTBR_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/SCN_WT_BTBR_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Liver_WT_BL6_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Plasma_WT_BL6_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/SCN_WT_BL6_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Liver_WT_BKS_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/Plasma_WT_BKS_groupedFC.csv ../GroupStatistics/Plot/
Rscript 8_PlotGroupStatistic.R ../GroupStatistics/SCN_WT_BKS_groupedFC.csv ../GroupStatistics/Plot/